### ISSUE TITLE
COUNT() should return INT

### ISSUE THREAD

**Issue by achalpandey** [cdapio/tigon#22]
As discussed earlier, since java doesn't support unsigned data types. Please change count() to return INT instead of UINT

**Comment by achalpandey** [comment]
Also, do we need to change UINT to INT, ULLONG to LLONG etc in the function definitions inside external_fcns.def ? As the java program will only return signed data values.

For e.g. Will the function str_truncate(string, uint) continue to work correctly?

**Comment by ted-johnson** [comment]
It returns int

**Comment by achalpandey** [comment]
Verified.
LGTM :+1:
