### ISSUE TITLE
Syntax error in generated files

### ISSUE THREAD

**Issue by achalpandey** [cdapio/tigon#51]
UPDATED

There are missing semi colons in the auto generated file (hfta_0.cc) when the SQL query contains an `INNER JOIN`

Update: It is not just INNER JOIN, other queries may fail as well.
# Schemas:

>   StreamSchema nameSchema = new StreamSchema.Builder()
>       .addField("uid", GDATFieldType.INT, GDATSlidingWindowAttribute.INCREASING)
>         .addField("name", GDATFieldType.STRING)
>         .build();
>       addJSONInput("nameInput", nameSchema);
> 
>    StreamSchema ageSchema = new StreamSchema.Builder()
>       .addField("uid", GDATFieldType.INT, GDATSlidingWindowAttribute.INCREASING)
>         .addField("age", GDATFieldType.INT)
>         .build();
>       addJSONInput("ageInput", ageSchema);
# Sample 1:

> SELECT nI.uid, nI.name, aI.age INNER_JOIN FROM nameInput nI, ageInput aI WHERE nI.uid = aI.uid AND aI.age > 40

Error Log:

> $ make
> g++ -O3 -g -I ../../include  -I ../../include/hfta -o hfta_0.o -c hfta_0.cc
> hfta_0.cc:272:1: warning: control reaches end of non-void function [-Wreturn-type]
> }
> ^
> hfta_0.cc:383:15: warning: shift count >= width of type [-Wshift-count-overflow]
>                 return( (0) >> 32);
>                             ^  ~~
> hfta_0.cc:499:11: error: expected ';' after return statement
>                 return 0
>                         ^
>                         ;
> hfta_0.cc:649:11: error: expected ';' after return statement
>                 return 0
>                         ^
>                         ;
> 2 warnings and 2 errors generated.
> make: **\* [hfta_0.o] Error 1
# Sample 2

> SELECT uid, COUNT(*) FROM nameInput nI GROUP BY uid

Error log:

> $ make
> gcc -O3 -g -I . -I ../../include -I ../../include/lfta -o lfta.o -c localhost_lfta.c
> localhost_lfta.c:297:17: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
>                 if((gb_attr_0 == t->aggr_table[probe].gb_var0)){
>                     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> localhost_lfta.c:297:17: note: remove extraneous parentheses around the comparison to silence this warning
>                 if((gb_attr_0 == t->aggr_table[probe].gb_var0)){
>                    ~          ^                              ~
> localhost_lfta.c:297:17: note: use '=' to turn this equality comparison into an assignment
>                 if((gb_attr_0 == t->aggr_table[probe].gb_var0)){
>                               ^~
>                               =
> localhost_lfta.c:757:17: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
>                 if((gb_attr_0 == t->aggr_table[probe].gb_var0)){
>                     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> localhost_lfta.c:757:17: note: remove extraneous parentheses around the comparison to silence this warning
>                 if((gb_attr_0 == t->aggr_table[probe].gb_var0)){
>                    ~          ^                              ~
> localhost_lfta.c:757:17: note: use '=' to turn this equality comparison into an assignment
>                 if((gb_attr_0 == t->aggr_table[probe].gb_var0)){
>                               ^~
>                               =
> 2 warnings generated.
> g++ -O3 -g -o rts lfta.o -L../../lib -lgscplftaaux -lgscprts -lgscphost -lm -lgscpaux -lgscplftaaux  -lclearinghouse -lresolv -lpthread -lgscpinterface  -lgscpaux -lcurl
> g++ -O3 -g -I ../../include  -I ../../include/hfta -o hfta_0.o -c hfta_0.cc
> hfta_0.cc:423:11: error: expected ';' after return statement
>                 return 0
>                         ^
>                         ;
> 1 error generated.
> make: **\* [hfta_0.o] Error 1

**Comment by achalpandey** [comment]
- To recreate this error please use the latest code from the develop branch on tigon repo.
- These problems did not exist in our old code (Sept 10). 

To access the old bin lib include cfg directories please use the the tarballs available at https://github.com/caskdata/tigon/tree/develop/tigon-sql/src/main/resources

**Comment by ted-johnson** [comment]
Can I get more context, how are nO and aI defined?

**Comment by ted-johnson** [comment]
I am not able to replicate this error.

In packet_schema.txt:

PROTOCOL ageInput  {
        int uid get_csv_int_pos1 (increasing);
        int age get_csv_int_pos2;
}

PROTOCOL nameInput  {
        int uid get_csv_int_pos1 (increasing);
        string name get_csv_string_pos2;
}

$more join_exl.gsql
DEFINE{
query_name 'jexl';
}
SELECT nI.uid, nI.name, aI.age INNER_JOIN FROM nameInput nI, ageInput aI WHERE nI.uid = aI.uid AND aI.age > 40

The build succeeds.

I am using the mergewithgs branch.
Can you try

1)      Sending me hfta_0.cc, that should help to identify the source of the discrepancy

2)      Is there some way to take a diff of the contents of your branch with the one I am using?

Please email me directly with a subject like “Ted look at this” as I am a) on vacation and b) get so much tigon spam I delete it in bulk.

Ted

**Comment by ted-johnson** [comment]
Achal,

Can you send me a specific set of git command lines needed to access the buggy branch.
Please note that

1)      I can’t get any gui interface to work, I use the command line interface only.

2)      Trying to figure out how to access a new branch generally takes me about a half day, and I’m on vacation and would rather not be spending it screwing around with github.

Ted

**Comment by prinam** [comment]
https://issues.cask.co/browse/TIGON-127
